Add function to set / unset credentials for Requests
Avaq/fp-ts-fetch pull request #1
Opened 2024-10-31 12:46 UTC by indebanvdhamer

This functionality is currently missing and I need it in my project where I use session cookies. The function to set the credentials uses the built-in `RequestCredentials` type

2024-10-31 12:51 UTC, Avaq commented on src/Request.ts
> +);
What does the .credentials getter return after explicitly setting it to undefined? Is it still a string (as expected by other parts of the code)?

2024-10-31 12:51 UTC, Avaq commented on src/Fetch.ts
> +      Req.unsetCredentials,
I wonder if, alternatively, we can explicitly downgrade "include" to "same-origin" for any request resulting from a redirection. I guess the end result would be the same, or should be, at least.

2024-10-31 12:59 UTC, indebanvdhamer commented on src/Fetch.ts
> +      Req.unsetCredentials,
I think this makes sense, I see this in the [specs](https://fetch.spec.whatwg.org/): `Unless stated otherwise, it is "same-origin".`

2024-10-31 13:02 UTC, indebanvdhamer commented on src/Request.ts
> +);
The type still shows `RequestCredentials`, which would not be true in this case. I think unsetting might be redundant if we just set the credentials to `same-origin` explicitly like you mentioned in your other comment.

2024-11-02 05:43 UTC, Avaq requested changes
LGTM. Could you also add it to the README?

2024-11-05 10:41 UTC, Avaq approved these changes

2024-11-05 10:41 UTC, merged